name: wah_frontend_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.3
  provider: ^6.1.2
  google_fonts: ^6.2.1
  intl_phone_field: ^3.2.0
  flutter_dotenv: ^5.0.2
  image_picker: ^1.0.0
  flutter_svg: ^1.1.0    
  carousel_slider: ^5.0.0
  qr_flutter: ^4.1.0
  intl: ^0.18.0
  flutter_emoji: ^2.0.0
  video_player: ^2.9.2
  open_file: ^3.5.4
  flutter_multi_select_items: ^0.4.3
  booking_calendar: ^1.1.10
  flutter_stripe: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # The following section is specific to Flutter packages.
  assets:
    - assets/
    - .env